### ISSUE TITLE
Missing dependencies from d3

### ISSUE THREAD

**Issue by hy0ug0** [ciena-frost/ember-frost-chart#21]
After running `ember install ember-frost-chart` there is still some packages missing.

> Could not find module `d3-scale` imported from `ember-frost-chart/helpers/d3-linear-scale`

After installing `ember-d3` and `d3` with `ember install ember-d3` and `npm install d3`, everything seems to work.

**Comment by notmessenger** [comment]
This has been resolved at some point, most likely in #40
